name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:

jobs:
  Testing:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Setup Composer and Dependencies
        uses: php-actions/composer@58260d1d3c7c1576becac3ac182175adf510e953 # v6
      - name: Run Tests
        run: symfony php bin/phpunit
        env:
            XDEBUG_MODE: coverage
#      - name: Run Tests
#        uses: php-actions/phpunit@8b81f7e713aba7ca15632bad78c56635ff327104 # v3
#        env:
#          XDEBUG_MODE: coverage
#        with:
#          version: 9.6.10
#          configuration: phpunit.xml.dist
#          php_extensions: xdebug
#          coverage_clover: coverage/clover.xml
#          coverage_html: coverage/report
      - name: Store Code Coverage Report
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: coverage
          path: coverage/

  Upload_Coverage_Report:
    name: Upload coverage report to Codecov
    needs: [Testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          fetch-depth: 2
      - name: Download Coverage Report
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: coverage
          path: coverage/
      - name: Codecov Upload
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage/
          fail_ci_if_error: true
